name: words-use
channels:
  - conda-forge
  - defaults
dependencies:
  - esda
  - fastparquet
  - geopandas
  - graph-tool
  - jupyterlab
  - matplotlib-base
  - networkx
  - numba
  - pip
  - plotly
  - pyarrow
  - pygeos
  - python
  - python-dotenv
  - python-louvain
  - scikit-learn
  - scipy
  - setuptools
  - pip:
    - clusim
    - infomap
    - POT
    - pycld2
    - pymongo
    - /home/thomaslouf/me/querier-0.0.5.tar.gz
    - ray
    - rectangle-packer
    - tqdm
    - wordcloud
