name: words-use
channels:
  - conda-forge
  - defaults
dependencies:
  - libpysal
  - esda
  - pandas
  - numexpr
  - bottleneck
  - pytables
  - fastparquet
  - geopandas
  - graph-tool
  - ipywidgets
  - jupyterlab
  - matplotlib-base
  - networkx
  - numba
  - pip
  - plotly
  - pyarrow
  - pygeos
  - python
  - python-dotenv
  - python-louvain
  - scikit-learn
  - scipy
  - setuptools
  - pip:
    - clusim
    - infomap
    - pycld2
    - pymongo
    - git+https://github.com/TLouf/querier.git
    - ray
    - rectangle-packer
    - tqdm
    - wordcloud
    - seaborn
    - -e ./