name: words-use
channels:
  - conda-forge
  - defaults
dependencies:
  - descartes=1.1.0
  - esda=2.3.6
  - fastparquet=0.5.0
  - geopandas=0.8.2
  - graph-tool=2.37
  - jupyterlab=3.0.7
  - matplotlib-base=3.3.4
  - networkx=2.5
  - numpy=1.20.1
  - pandas=1.2.3
  - pip=21.0.1
  - plotly=4.14.3
  - pyarrow=3.0.0
  - pygeos=0.9
  - python=3.7.9
  - python-dotenv=0.15.0
  - python-louvain=0.15
  - scikit-learn=0.24.1
  - scipy=1.6.0
  - setuptools=49.6.0
  - shapely=1.7.1
  - pip:
    - clusim==0.4
    - infomap==1.3.0
    - POT==0.7.0
    - pycld2==0.41
    - pymongo==3.11.2
    - querier==0.0.5
    - ray==1.2.0
    - rectangle-packer==2.0.0
    - tqdm==4.56.2
